### PR TITLE
i18n: Nepali translation🇳🇵

### PR DESCRIPTION
**Pull request by ankitpokhrel**
### Summary

This PR adds Nepali translation to gherkin parser.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Hi @ankitpokhrel,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by aslakhellesoy** [comment]
Thanks for merging this @luke-hill 

Please always make sure the PR's build is green before merging. This one was red when you merged it. The reason it was red is that the `gherkin/gherkin-languages.json` file has not been synched into the language subfolders (`gherkin/*/gherkin-languages.json`).

This is done with `source scripts/functions.sh && rsync_files` and then committing.

I will improve the build error message to make it more obvious that this is what needs to be done.

**Comment by aslakhellesoy** [comment]
Also, please always update the CHANGELOG when you merge a PR. Not only do users use it to know what was changed in a release, we contributors use it to decide whether to bump the patch, minor or major version when we make a new release.

**Comment by luke-hill** [comment]
Yeh, that build job I've never seen pass. It always fails for some permissions issue. It's been that way for me for months.

**Pull request merged**
