### PR TITLE
cucumber-expressions: remove node 8 support

### LINKED ISSUE #738: Remove dependency on xregexp when Node8 is EOL
We should revert the change in https://github.com/cucumber/cucumber/pull/732 once we no longer need to support Node8

### PR DESCRIPTION
**Pull request by davidjgoss**
## Summary

Remove code and CI config that supports Node 8.

## Details

- Remove Circle CI config that builds the expressions javascript library against Node 8
- Remove the regexp compatibility library that was only required to support Node 8

## Motivation and Context

Fixes #738.

Node 8 LTS [ends tomorrow](https://nodejs.org/en/about/releases/), which means cucumber no longer needs to support it. 

## How Has This Been Tested?

Covered by existing unit tests, which still pass.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected) - as we are removing support for a platform version

## Checklist:

- [ ] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [ ] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Nice one @davidjgoss. Are you OK with removing Node 8 support from cucumber-js @charlierudolph? If so, please go ahead and merge @davidjgoss, adding `CHANGELOG` section under `## Removed` so we remember to bump the major version when we make a release.

**Comment by aslakhellesoy** [comment]
@charlierudolph ping?

**Comment by charlierudolph** [comment]
Sorry, yep, agreed. Been following Node LTS for what cucumber-js supports

**Comment by davidjgoss** [comment]
Thanks, also raised https://github.com/cucumber/cucumber-js/pull/1276 to drop node 8 from cucumber-js CI

**Comment by aslakhellesoy** [comment]
@davidjgoss what's in this PR? GitHub says  76,292 files have changed??

**Comment by aslakhellesoy** [comment]
Looks like you've checked in tons of `node_modules` in 32cfd30220d9c5059881da07618c482a6ed5439a

We have to revert this and maybe do some git magic to prevent this from creating a huge history. I don't have time to do this now, can you look into this please?

**Comment by davidjgoss** [comment]
Whoa, not sure what happened there, I merged master, fixed a conflict and could have sworn it still said 4 files changed.

Will revert the node modules now and look into what we can do about the history (without rewriting history on master)

**Comment by aslakhellesoy** [comment]
@davidjgoss I've done the following as per your [suggestion](https://cucumberbdd.slack.com/archives/C612KCP1P/p1579122504014000):

```
git reset c692a37ae && git push -f
```

It seems fine now. Can you create a new PR please and merge that?

**Pull request merged**
