### PR TITLE
gherkin: Update gherkin-c to the current gherkin status

### PR DESCRIPTION
**Pull request by brasmusson**
## Summary

Update gherkin-c to the current gherkin status.

## Details

This PR has two commits.
The first commit updates gherkin-c to gherkin v6.0.17 status, that is with that commit applied on top of the tag `gherkin/v6.0.17` the acceptance test passes for gherkin-c.
The second commit updated gherkin-c to the current status of the master branch - primarily by calculating the pickle id for the pickles. 

## Motivation and Context

Update gherkin-c beyond gherkin v5 status.

## How Has This Been Tested?

Tested using the gherkin acceptance test using gcc 7.4.0.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [X] Making one gherkin implementation consistent with the other gherkin implementations.

## Checklist:

- [ ] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [ ] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Awesome work @brasmusson!

To make this complete the `gherkin/Makefile` should also be modified to re-enable the build. `.circleci/config.yml` should be update too, so it's built by CircleCO

**Comment by brasmusson** [comment]
Now gherkin-c is activated in `gherkin/Makefile` and the CircleCI configuration updated to also have a job for gherkin-c.

**Comment by cyocum** [comment]
Wow. This is great. Thanks @brasmusson! I will need to test this against cucumber.ml to make sure it will all still work.  If it doesn't, I will need to make changes and create a new release.

**Comment by cyocum** [comment]
I was able to spend a bit of time of this today.  I have a question: does the VERSION file need to be updated as rules are in Gherkin 6?

**Comment by cyocum** [comment]
OK, I have done a test compile and I will need to do a bunch of changes to make this work.  It would be helpful to have the versions tagged so users can at least find their way around the problem while I fix the incompatibilities.

**Comment by brasmusson** [comment]
When we are confident in the implementation we should probable push https://github.com/cucumber/cucumber/pull/671/commits/6e3fc3f881cafc696c5e36ed947cfc667f8f9c8a together with changes of `CMakeLists.txt` and `VERSION` to the gherkin-c sub-repo and tag it a `v6.0.17`. https://github.com/cucumber/cucumber/pull/671/commits/7b77fc702cd191b43bc0aec2b4b1101f30bad377 on the other hand belong to the still unreleased version 7 of gherkin.

**Pull request merged**
