### PR TITLE
Modified docs as per suggestions and cleared the mess

### PR DESCRIPTION
**Pull request by gmk1217**
Modified documents as per suggested changes added cucumber.md and living documentation.md

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Are you creating a new PR every time you are making a modification? Please don't do that - just push new commits to the existing PR. You have 4 open pull requests now - #36, #38, #39, #40, and there seems to be dependencies and duplication between them. This makes it too hard for us to approve your pull requests.

* Each pull request should not modify several (unrelated) documents.
* The title of each pull request should explain what document you're adding/changing.

Have a read through the [contribution guidelines](http://docs.cucumber.io/docs/contributing-to-documentation.html) again please.

**Comment by gmk1217** [comment]
@aslakhellesoy : yeah i messed up and confused every i created a pull request. My sincere apologies for creating a mess. 
Now I am clear and wouldnt repeat it again... :)

**Comment by aslakhellesoy** [comment]
No worries @gmk1217 - we're very grateful for your help! Maybe it's best if you close all your existing pull requests and submit new ones, where each PR is for one document? And none of the PRs depend on other PRs?

I'm still concerned about copying content from other sites. All our content should be original.

**Comment by gmk1217** [comment]
ok will close duplicate PRs .
Hmm its not mandatory to have those paragrahs there, since they added value to the doc, I added them ... still if you guys have concern on those i will delete them..

**Comment by mattwynne** [comment]
Thanks for working with us on this @gmk1217. In general, small PRs are better - when there's less to consider and discuss, they'll flow through the review process faster.

**Comment by gmk1217** [comment]
Agreed. Will adopt and make thngs easy for you guys.

**Pull request closed without merging**
