### PR TITLE
gherkin: Add new word to russian translation.

### PR DESCRIPTION
**Pull request by Pr-Mex**
## Summary

Added new word into russian translate.

## Motivation and Context

Allows more flexible use of the Gherkin language.

### CODE REVIEW

**Comment by tsundberg** [comment]
Is anyone able to explain why this build failed?

A Docker process exited with 2 and the build exited with 0. Travis is upset because the build exited with 1. But I can't see where that would have been.

**Comment by brasmusson** [comment]
The `eslint src test` for cucumber-expressions/javascript failed, see line 4390-4431 in the log, making the first script in the [.travis.yml](https://github.com/cucumber/cucumber/blob/master/.travis.yml#L7) fail.

**Comment by aslakhellesoy** [comment]
I'll have a look

**Comment by aslakhellesoy** [comment]
The build was broken due to linting errors a couple of weeks ago (when @Pr-Mex branched off). It's fixed now, but this PR is still branched off from the broken build.

This should be safe to merge.

**Comment by aslakhellesoy** [comment]
After merging changes to gherkin translations like this, please run the following:

```
./scripts/docker-run Dockerfile.cucumber-build make clean
./scripts/docker-run Dockerfile.cucumber-build make
```

This should regenerate some files. Commit and push.

**Comment by aslakhellesoy** [comment]
Wanna give it a go @tsundberg ?

**Comment by tsundberg** [comment]
Sure, I'll do it tomorrow.

**Comment by aslakhellesoy** [comment]
Hi @Pr-Mex,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by aslakhellesoy** [comment]
Thanks for merging this @tsundberg. Did you do what I explained [above](https://github.com/cucumber/cucumber/pull/305#issuecomment-350089570)? I had expected to see additional commits as a result of that.

@Pr-Mex should get recognition for his contribution, and other users of Cucumber should be made aware of it. For this we use a `CHANGELOG.md` file.

Could you update that please?

**Comment by aslakhellesoy** [comment]
My bad about the `make` instructions above @tsundberg - looks like the `Makefile`'s got some missing dependency rules so it doesn't rebuild what it should. I'll push a fix for that soon.

**Comment by tsundberg** [comment]
Cool, I was a bit surprised when there wasn't any changes. Please ping me when you are done and I will give it a new go.

**Comment by aslakhellesoy** [comment]
Go for it!

**Comment by aslakhellesoy** [comment]
And don't forget about updating `CHANGELOG` @tsundberg

**Pull request merged**
