### PR TITLE
Fix gherkin for tagging rules

### PR DESCRIPTION
**Pull request by sebrose**
## Summary

Fixes: #1123

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [x] The change has been ported to Java.
- [x] The change has been ported to Ruby.
- [x] The change has been ported to JavaScript.
- [x] The change has been ported to Go.
- [x] The change has been ported to .NET.
- [x] I've added tests for my code.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the CHANGELOG accordingly.

### CODE REVIEW

**Comment by ehuelsmann** [comment]
@sebrose what's the process on this branch? Do I add commits for the Perl implementation to support this change in the grammar? If so, I'm not sure when, as the change in the grammar still seems under discussion.

**Comment by ehuelsmann** [comment]
@brasmusson thanks for the Perl part. Looking good.

**Comment by brasmusson** [comment]
Now the CI build is green. However, the fix the make `gherkin-elixir` use the `messages-elixir` build locally from the monorepo is just a hack: https://github.com/cucumber/cucumber/pull/1356/commits/4b85694837191912a41314b924a22772675db93c. I'm not familiar enough with the Elixir packaging and dependency system to how to only use the local dependency when building the monorepo (and not also after releasing `gherkin-elixir`.

**Comment by sebrose** [comment]
The build is green due to a fix for the Gherkin Elixir build contributed by @brasmusson. He characterises the fix as a hack and we could do with input from someone who has more knowledge of Elixir.

**Comment by aslakhellesoy** [comment]
@sebrose you marked this as ready for review, but there are conflicts with master that must be resolved first

**Comment by sebrose** [comment]
@aslakhellesoy Please see my comment

**Comment by aslakhellesoy** [comment]
Thanks - I’ll look at the Elixir stuff.

There are 3 conflicting files that aren’t Elixir related. Have you tried resolving those?

**Comment by sebrose** [comment]
It's on my list : )

**Comment by WannesFransen1994** [comment]
@sebrose and @brasmusson , thank you both for the hard work and taking the time to look at the elixir package!

I've adjusted the makefiles, since the `{:cucumber_messages, "~> 13.2", path: "../../messages/elixir"}` dependency is strange in my opinion. (honestly, I was surprised it compiles. And even if it compiles, will it use the local or remote dependency...?) Normally it is either one of the following according to the [elixir dependency docs](https://hexdocs.pm/mix/Mix.Tasks.Deps.html):

* `{:local_dependency, path: "your/path"}`
* `{:remote_dependency, "version"}`

That's why I've updated the `mix.exs` file to use the approach of commenting the remote/local dependency, e.g.:

```elixir
      # {:cucumber_messages, "~> 13.2"},
      {:cucumber_messages, path: "../../messages/elixir"},
```

As for the makefile, I've done my best to keep this as "clean" as possible, but this can probably be done a lot better...

**Comment by gasparnagy** [comment]
We merged master into this to be able to fix the merge conflicts. Maybe rebase would have been nicer... :)

**Comment by aslakhellesoy** [comment]
Is this still a draft, or is this ready for review and merge?

**Comment by WannesFransen1994** [comment]
Short question, if [generated code files aren't expected to be included in the repository](https://github.com/cucumber/cucumber/pull/1367#issuecomment-789000889), how can we compile the elixir-gherkin library when referring to it through a path? ^^'

Should I do something in the makefiles or? :sos: @aurelien-reeves

**Comment by aslakhellesoy** [comment]
> how can we compile the elixir-gherkin library when referring to it through a path

@WannesFransen1994 we do this by building `messages` before `gherkin`. There are several such dependencies in the monorepo, and they are defined in two places:

* `/Makefile` where `messages` is build before `gherkin`
* `.circleci/config.yml` where inter-dependencies are defined in the `jobs` section using `requires:`.

For the latter to work, each job that produces files that are needed by a downstream job have to persist them using `persist_to_workspace`.

**Comment by WannesFransen1994** [comment]
I think that the build is failing due to the newly merged messages.proto and gherkin-elixir is now trying to build with the new messages library, while gherkin-elixir isn't supporting it yet.

I'll take a look at it this weekend / monday, apologies for the delay.

**Comment by aslakhellesoy** [comment]
Great! I tried to fix it, but quickly realised I need to learn some basic Elixir first :-)

**Comment by brasmusson** [comment]
@WannesFransen1994 `{:cucumber_messages, "~> 14.0", path: "../../messages/elixir"}` does not compile if the dependency in the local path does not conform to the version statement. I changed the version statement to "~> 15.0" and then I go this when compiling gherkin-elixir:
```
Unchecked dependencies for environment test:
* cucumber_messages (../../messages/elixir)
  the dependency does not match the requirement "~> 15.0", got "14.0.1"
** (Mix) Can't continue due to errors on dependencies
```
So it seems that `{:cucumber_messages, "~> 14.0", path: "../../messages/elixir"}` "use the dependency from the local path, but also verify that the version there conforms to the version statement.

**Comment by brasmusson** [comment]
The latest build failure of gherkin-elixir here, is actually coming from the master branch. gherkin-elixir on the master is not working with messages-elixir on the master (after the updated of `message.proto`), but since gherkin-elixir on the master is set up to use the released messages-elixir the error does not show up on the ci build on the master branch. Well, not I seems to have managed to fix the problem.

**Comment by WannesFransen1994** [comment]
> @WannesFransen1994 `{:cucumber_messages, "~> 14.0", path: "../../messages/elixir"}` does not compile if the dependency in the local path does not conform to the version statement. I changed the version statement to "~> 15.0" and then I go this when compiling gherkin-elixir:
> 
> ```
> Unchecked dependencies for environment test:
> * cucumber_messages (../../messages/elixir)
>   the dependency does not match the requirement "~> 15.0", got "14.0.1"
> ** (Mix) Can't continue due to errors on dependencies
> ```
> 
> So it seems that `{:cucumber_messages, "~> 14.0", path: "../../messages/elixir"}` "use the dependency from the local path, but also verify that the version there conforms to the version statement".

I had no idea! Thank you for explaining it. 



> The latest build failure of gherkin-elixir here, is actually coming from the master branch. gherkin-elixir on the master is not working with messages-elixir on the master (after the updated of `message.proto`), but since gherkin-elixir on the master is set up to use the released messages-elixir the error does not show up on the ci build on the master branch. Well, not I seems to have managed to fix the problem.

Yes, thank you for this!

**Comment by aslakhellesoy** [comment]
@gasparnagy @sebrose the only missing thing now is to update `messages/CHANGELOG.md` and `gherkin/CHANGELOG.md`. Try to make sure you put the changes under the right headings, as we use this to decide whether the next release should be a major, minor or patch bump.

Great work!!!!!!!!!

**Pull request merged**
