### PR TITLE
Triage process / Harmonize issue labels

### PR DESCRIPTION
**Pull request by aslakhellesoy**
## Summary

Use a consistent set of labels across repositories in this organisation.

## Details

A bash script that creates/updates labels across select repositories

## Motivation and Context

As discussed in [last week's community meeting]() we want to establish a triage process for issues and pull requests. This is to lower the cognitive overhead for regular contributors.

For this purpose, a [GitHub Projects Board](https://github.com/orgs/cucumber/projects/8) has been created. We want to use a consistent set of labels (with identical colour and description) so that the board will be easier to read.

I've set up a temporary repository with these labels [here](https://github.com/cucumber/label-demo/labels).

Before this is rolled out we need to:

* [ ] Manually rename existing labels
* [ ] Remove remaining labels that are not in the proposed standard set
  * An exception will be made for the `cucumber/cucumber` monorepo, which needs additional tags to separate between modules and languages.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
@cucumber/committers - any objections or suggestions before I start harmonising labels?

**Comment by robzenn92** [comment]
Awesome ! 👍

**Comment by davidjgoss** [comment]
Looks good. Did we decide what to do with “discussions”?

**Comment by aslakhellesoy** [comment]
> Looks good. Did we decide what to do with “discussions”?

I think the new GitHub discussions look great, but I'm afraid it would cause too much fragmentation. We already have Slack, GitHub issues/PRs and the [SmartBear Community](https://community.smartbear.com/).

Whenever people open an issue that looks like a question / discussion, I suggest we:

* Tag it with `❓ question`
* Leave a canned comment (mine says `Please use the [support](https://cucumber.io/tools/cucumber-open/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.`)
* Close the issue

(Just realised the support page still mentions the defunct google group - I've made a note to update that).

**Review by davidjgoss — APPROVED** [review]

**Comment by cbliard** [comment]
"Slow Burner" tag is used to prevent stalebot from closing the issue if inactive for too long.

In my opinion, "Slow Burner" is obfuscating the real intent of this tag. I suggest to rename "Slow Burner" tag to stalebot's default "pinned" which is more widely used and recognized.

Thoughts?

**Comment by aslakhellesoy** [comment]
I like pinned (with a 🧷 ) - will go for that!

**Comment by gebezs** [comment]
The Spring project has the `waiting-for-feedback` and `feedback-provided` labels. The `waiting-for-feedback` is a manual label with a `@` mention and the `feedback-provided` is an automated label change.
image

It is pretty useful to filter the issues where someone provided the required information for an `incomplete` issue.

Also the Spring team uses the `waiting-for-triage` to filter incoming issues but I am not sure how useful that is.

**Comment by mpkorstanje** [comment]
I'd second the `status` and `kind` prefixes.

**Comment by aslakhellesoy** [comment]
I agree various workflow labels are useful. I'll leave them out for this PR - we can add them later. I think there might be [bots](https://probot.github.io/) that can help us out with that.

**Comment by luke-hill** [comment]
I'm agnostic to the "what" but I do like the "why"

**Review by lopesc — APPROVED** [review]
Well done

**Comment by aslakhellesoy** [comment]
I have rolled out the harmonized tags to the most active repos. I've also filled up the new [board](https://github.com/orgs/cucumber/projects/8) according to the guidelines in the new `TRIAGE.md` document. In short, the issues in `Next`:

* consists of a mix of languages
* are a mix of PRs and `bug` issues
* they are all "old" (following a FIFO pull policy)

/cc @aurelien-reeves

**Pull request merged**
