### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by tsundberg**
`22` should have been `42` in `cucumber-expressions/README.md`

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
No need to send a PR for small changes like this @tsundberg - feel free to commit to master. You have write access don't you?

**Comment by tsundberg** [comment]
I don't have write access to `cucumber/cucumber`
I would have committed directly if I had.

**Comment by aslakhellesoy** [comment]
Try again @tsundberg

**Comment by tsundberg** [comment]
It works now. 
Thanks @aslakhellesoy

**Pull request merged**
