### PR TITLE
messages: Add the message proto to go's cucumber-messages package

### PR DESCRIPTION
**Pull request by dixonwille**
## Summary

I generated the message for go using the make file. I went ahead and updated the gherkin go to look for version 3.0.2 as well so that it will look for the proper version when running go get.

## Motivation and Context

https://github.com/cucumber/cucumber/issues/660

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [ ] The change has been ported to JavaScript.
- [x] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by dixonwille** [comment]
So I see that gherkin-go build failed... I am not familiar enough with the protoc version you guys are using. I could be using a different version?

**Comment by dixonwille** [comment]
I just pulled the latest protoc and it didn't make any changes to the message...

**Comment by dixonwille** [comment]
Open to suggestions to get the file generating correctly.

**Comment by aslakhellesoy** [comment]
Thanks for the fix @dixonwille!

In order to ensure a consistent toolset for contriutors we're providing a docker image that can be used for builds. See [CONTRIBUTING_NEW](https://github.com/cucumber/cucumber/blob/264599e393b16301716e1c40ff2a68b5f1e86148/CONTRIBUTING_NEW.md#building-on-docker)

**Comment by aslakhellesoy** [comment]
This is now fixed on master

**Pull request closed without merging**
