### PR TITLE
[WIP] ProtocolBuffers

### PR DESCRIPTION
**Pull request by aslakhellesoy**
## Summary

Use protobuf for all event protocol structs.

## Motivation and Context

Protocol buffers makes it easy to exchange data between processes. It provides a stronger contract than the NDJSON we're currently using. The schema is easier to maintain than JSON Schema, and code generation simplifies development.

I suggest this PR remove the use of "custom" structs (Java, .NET etc) and use Protobuf instead.
Tests can still use NDJSON, taking advantage of protobuf's JSON support.

@charlierudolph - this branch is based on your initial `cr-proto` branch. I suggest we continue work on this `proto` branch. It's easier to have collective code ownership when branches don't belong to anyone.

### CODE REVIEW

**Comment by mpkorstanje** [comment]
Would it be possible to exclude the generated files from git and regenerate them from source when building?

**Comment by aslakhellesoy** [comment]
Absolutely! I don't think I added any generated files yet?

**Comment by mpkorstanje** [comment]
You wrote 1k files by hand? Wow. :D

**Comment by mpkorstanje** [comment]
Ah I see now. This is the testdata copied a few times over.

**Comment by charlierudolph** [comment]
It appears `messages/javascript/index.js` should be removed and gitignored

**Comment by charlierudolph** [comment]
Cool. @aslakhellesoy how can I help with this? I wanted to get back to the protobuf work.

**Comment by aslakhellesoy** [comment]
Superceded by #416

**Pull request closed without merging**
