### PR TITLE
gherkin-python: Sync the release process with tag-expressions-python

### PR DESCRIPTION
**Pull request by brasmusson**
## Summary

Sync the release process with tag-expressions-python

## Details

* rsync the default.mk from .templates
* Include default.mk in the Makefile
* Update setup.py
  * Change to use double quotes (") instead of single quotes (') to
    enable the use of the update-version make rule
  * Change the download_url the publish make rule uploads the release
    archive to pypi (which was not done earlier for the gherkin-python
    releases).
  * Add (a short) long_description and platforms so that the PKG-INFO
    in the created distribution does not have any entries with the value
    UNKNOWN
* Commit the MANIFEST (which was updated when testing to create the
  source distribution locally).

## How Has This Been Tested?

Locally tested `update-version` and `python2 setup.py sdist` (the latter is the first have of the `publish` make rule).

## Types of changes

- [X] Bug fix in the release process for gherkin-python (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected). 

## Checklist:

- [ ] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [ ] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the CHANGELOG accordingly.

### CODE REVIEW

**Comment by brasmusson** [comment]
@aslakhellesoy I recon that cukebot needs to be added as a maintainer of https://pypi.org/project/gherkin-official/ (as it is for https://pypi.org/project/cucumber-tag-expressions/)

**Comment by aslakhellesoy** [comment]
Thanks @brasmusson !

**Comment by aslakhellesoy** [comment]
I've made `cukebot` an owner of `gherkin-official`.

**Comment by aslakhellesoy** [comment]
Version 18.1.0 is out! https://pypi.org/project/gherkin-official/#history

@jenisys in case you want to update behave to use this.

**Pull request merged**
