### PR TITLE
Fixing ISO 639-1 code for Telugu language

### LINKED ISSUE #1221: Language codes in gherkin-languages.json
## Summary
It appears the language codes used in `gherkin-languages.json` file do not follow ISO language codes (ISO 639-X). Using the ISO language codes is more common in most software development. Any plans on changing the codes?

### PR DESCRIPTION
**Pull request by nvmkpk**
## Summary
Updated the ISO 639-1 language code for Telugu

## Details
The file gherkin-languages.json has code for Telugu listed as `tl` but [ISO 639-1](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=te) code is `te`.

## Motivation and Context
The current language code used is incorrect as per ISO 639-1.

Fixes #1221

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [ ] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the CHANGELOG accordingly.

### CODE REVIEW

**Review by mpkorstanje — COMMENTED** [review]
Looks good.

Don't forget to add an entry to the CHANGELOG.

 https://github.com/cucumber/cucumber/blob/master/gherkin/CHANGELOG.md

**Comment by nvmkpk** [comment]
What version should this be added under?

**Comment by gmk1217** [comment]
Can you guys please throw some light on which IDEs Support Telugu language?
---

Thanks,

Mohan G

**Comment by mpkorstanje** [comment]
@nvmkpk  you can add it under the `Unreleased` version. Our release scripts will automatically change that to a version number when we make the release.

**Comment by aslakhellesoy** [comment]
Hi @nvmkpk,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
