### PR TITLE
gherkin: Prefer `require_relative` for internal requires

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## Summary

This PR changes internal requires inside the `gherkin-ruby` gem to use `require_relative`. 

## Details

`require_relative` is faster because it doesn't search the `$LOAD_PATH`, it's more clear, because it makes it more explicit where the code is being loaded from, and it can avoid actually requiring the wrong code.

Normally this doesn't make a difference, but in this case, since the same files are also present in the old defunct `gherkin` gem (if I have understood the migration alright), it can prevent errors.

In my case, I was upgrading `cucumber`, but some dependencies still were pinned to the old `gherkin` gem. This was causing some requires to actually load code from the old project, causing weird errors like:

```
1 processes for 1 features, ~ 1 features per process
wrong number of arguments (given 1, expected 0) (ArgumentError)
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/gherkin-5.1.0/lib/gherkin/ast_builder.rb:5:in `initialize'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-gherkin-13.0.0/lib/gherkin/stream/parser_message_stream.rb:15:in `new'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-gherkin-13.0.0/lib/gherkin/stream/parser_message_stream.rb:15:in `initialize'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-gherkin-13.0.0/lib/gherkin.rb:19:in `new'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-gherkin-13.0.0/lib/gherkin.rb:19:in `from_sources'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-gherkin-13.0.0/lib/gherkin.rb:27:in `from_source'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-core-7.0.0/lib/cucumber/core/gherkin/parser.rb:20:in `document'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-core-7.0.0/lib/cucumber/core.rb:33:in `block in parse'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-core-7.0.0/lib/cucumber/core.rb:32:in `each'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-core-7.0.0/lib/cucumber/core.rb:32:in `parse'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-core-7.0.0/lib/cucumber/core.rb:24:in `compile'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-4.0.0/lib/cucumber/runtime.rb:78:in `run!'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-4.0.0/lib/cucumber/cli/main.rb:29:in `execute!'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/cucumber-4.0.0/bin/cucumber:9:in `<top (required)>'
/home/deivid/.rbenv/versions/2.7.1/bin/cucumber:23:in `load'
/home/deivid/.rbenv/versions/2.7.1/bin/cucumber:23:in `<top (required)>'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:481:in `exec'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:24:in `start'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0.dev/exe/bundle:49:in `block in <top (required)>'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/site_ruby/2.7.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0.dev/exe/bundle:37:in `<top (required)>'
/home/deivid/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
/home/deivid/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
Tests Failed
```

## How Has This Been Tested?

I made the edits in place and confirmed that my issue was gone.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [ ] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the CHANGELOG accordingly.

### CODE REVIEW

**Comment by vincent-psarga** [comment]
That seems nice :) I'm wondering if that's the kind of thing we could/should enforce with rubocop rules ?

**Comment by deivid-rodriguez** [comment]
That would be nice, yeah,m although I don't think rubocop can do that at the moment.

Is build failure unrelated, by the way?

**Comment by vincent-psarga** [comment]
> Is build failure unrelated, by the way?

I'm having a look, I remember having troubles with the way locations where rendered in json.

**Comment by vincent-psarga** [comment]
Ok, the Gemfile was not pointing to `cucumber-ruby` 3.x (which was our target for `json-formatter`).
I'll wait for the build to pass to get this merged.

**Comment by deivid-rodriguez** [comment]
Thanks @vincent-psarga!

**Pull request merged**
