### PR TITLE
Properly close HTML formatter pre tag for leading comment

### LINKED ISSUE #828: Comments in feature-file cause issues in html-report
Cucumber-version: 2.0.0 (also seen and reported on cuke-devs-mailinglist on 2.0.0.beta2)

Seems there is a `<pre class=comment>` which spans everything inside the feature-div in the report ... makes everything look odd (like too much space between elements) ... I guess this might be triggered by the feature file starting with a comment (like `# encoding: UTF-8` or `# language: no` )

```
<div class="feature">
	<pre class="comment"># encoding: UTF-8<br>
		<h2>
			<span class="val">Feature: Watir-webdriver works with cucumber</span>
		</h2>
		<p class="narrative">As developers<br>
			To not kick the bucket from the boredom of manual web testing<br>
			We want watir-webdriver and cucumber to work<br>
		</p>
		<div class="scenario">
			<span class="scenario_file">features/watir-works.feature:8</span>
			<h3 id="scenario_1" style="cursor: pointer;"><span class="keyword">Scenario:</span> <span class="val">Google search for agurk</span></h3>
			<ol>
				<li id="" class="step passed">
					<div class="step_name"><span class="keyword">Given </span><span class="step val">we're on the google search page</span></div>
					<div class="step_file"><span>features/step_definitions/agurk_steps.rb:3</span></div>
				</li> 
				<script type="text/javascript">moveProgressBar('100.0');</script>
				<li id="" class="step passed">
					<div class="step_name"><span class="keyword">When </span><span class="step val">we search for "<span class="param">agurk</span>"</span></div>
					<div class="step_file"><span>features/step_definitions/agurk_steps.rb:7</span></div>
				</li> 
				<script type="text/javascript">moveProgressBar('100.0');</script>
				<li id="" class="step passed">
					<div class="step_name"><span class="keyword">Then </span><span class="step val">we should find the term in the page</span></div>
					<div class="step_file"><span>features/step_definitions/agurk_steps.rb:13</span></div>
				</li> 
				<script type="text/javascript">moveProgressBar('100.0');</script>
			</ol>
		</div>
	</pre>
</div>
```
See also attached screenshot.

cuke-pre-issue

### PR DESCRIPTION
**Pull request by pdswan**
closes #828

### CODE REVIEW

**Comment by brasmusson** [comment]
@pdswan A tip, when you create a pull request for fixing an issue, do include "fixes #<nr>" in the description of the pull request (or any of the other [keywords for closing issues](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues)), then the issue will be closed automatically when the pull request is merged. "see #<nr>" is not nearly as good, since it only creates a link to the issue, the issue will have to be closed manually when the pull request is merged (and yes, pull request descriptions can be edited after the pull request is created).

**Comment by mattwynne** [comment]
...and also thanks @pdswan ;)

**Comment by mattwynne** [comment]
Seriously, I do think this kind of edge-case would be better tested with a unit-test. The `pretty_specs` are in good shape IIRC and should be easy enough to add this example to. Did you try @pdswan?

**Comment by pdswan** [comment]
@brasmusson that's certainly much more useful, isn't it. updated.

@mattwynne agreed and moved. could have sworn i looked for an appropriate unit spec last night :confused:

**Comment by brasmusson** [comment]
Merged, thanks for your contribution @pdswan.

**Pull request merged**
