### PR TITLE
I18N French: Add "Sachant que" as Given, and "Donc" as Then

### PR DESCRIPTION
**Pull request by domi41**
## Motivation and Context

```gherkin
Feature: Add more keyword aliases
  In order to engage algorithmically illiterate people
  As a gherkin runner
  I want to provide the idiomatic keywords they use
```

## How Has This Been Tested?

This commit is untested, but the words are already loved and used in our features by our non-technical people.

## Types of changes

Poetry?

## Checklist:

- [ ] I've added tests for my code.
  > Are there tests for each language ?

### CODE REVIEW

**Comment by luke-hill** [comment]
@domi41 to answer your question though, there are tests for a variety of languages (But not them all).

Here is a Norwegian test in Ruby: https://github.com/cucumber/cucumber/blob/master/gherkin/ruby/spec/gherkin/gherkin_spec.rb#L339-L350

**Comment by aslakhellesoy** [comment]
Hi @domi41,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by aslakhellesoy** [comment]
I was on easter holiday and didn't have a chance to comment on this.

I'm not too keen on this inflation of synonyms. "Sachant que" (or "Knowning that") does not feature in any other translation AFAIK, so why should we make an exception for French?

I also think "Sachant que" is a bit misleading for what the purpose of Given step is. Knowing something sounds a bit like there isn't anything to *do* - it just *is*.

@domi41 can you provide some examples of sentences that sound mroe idiomatic with "Sachant que" than "Etant donne" or "Soit"? (I'm fluent in French)

**Comment by aslakhellesoy** [comment]
Hi @luke-hill - we'll see what @domi41 comes back with - I may ask you to revert this.

**Comment by domi41** [comment]
Hello ! Thanks for the warm welcome @luke-hill @aslakhellesoy !

> Knowing something sounds a bit like there isn't anything to do - it just is.

You're right.

The "Knowing that" in our suite can be viewed as __sanity checks__.
They never effect anything, that's what make them conceptually different from "Given", and therefore more idiomatic in our scenarios.

Those _sanity checks_ are not for the code (even if that's useful), they exist for the **brains of the readers**, to make the scenarios more explicit, and easier to apprehend.  They provide reassurance for people who are less accustomed as we are to the state of defaults, or even the state of things during a scenario.

```gherkin
Scénario: S'inscrire anonymement en tant que citoyen⋅ne
  Sachant qu'il ne devrait y avoir aucun⋅e citoyen⋅ne dans la base de données
    Quand je m'inscris en tant que citoyen⋅ne avec le jeton "g4ulo1s_réfr4ctR!"
    Alors il doit maintenant y avoir un⋅e citoyen⋅ne dans la base de données
```

The people who want this are pleading for _poetic license_.
They say reading the sanity check using "Sachant" is easier on their brains (i agree).

With training they might learn to not need the sanity checks altogether.
But we're precisely using Gherkin features for their accessibility.

Synonym inflation is natural, as more people discover the tool.  It should wane at some point, but are we there yet?

---

Transforming literal quantities like `un⋅e` or `quatre-vingt seize` to integers is _loads of fun_, in modern epicène french.

**Comment by aslakhellesoy** [comment]
Thanks for the clarification @domi41!

What do you typically do in a step defionition of a "Sachant que" step? Do you make an assertion about expected state?

**Comment by domi41** [comment]
> What do you typically do in a step defionition of a "Sachant que" step? Do you make an assertion about expected state?

Yes, those are assertions about states ; in the idiom, they also sometimes are no-op steps that remind a Rule expressed above, to clarify the behavior of a scenario.

When you put it that way, "Sachant" is a "Then" more than a "Given"…

**Comment by aslakhellesoy** [comment]
Hi @domi41,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
