### PR TITLE
Try cucumber

### PR DESCRIPTION
**Pull request by aslakhellesoy**
## Summary

Try Cucumber in the browser

## Motivation and Context

People who are new to Cucumber should be able to try it out without installing it, to get an idea of what it is.

They should learn about the following:
* Gherkin
* Step definitions and Cucumber expressions
* BDD cycle

It should be done in an environment that:
* Gives the user small tasks to complete, to learn the basics
* Provide feedback when the user is stuck
* Provide an intuitive UI that has visual cues to explain the correlation of steps, expressions, parameters, arguments, step definitions and so on.

## How Has This Been Tested?

Manually, it's very much a spike at this point

## Screenshots (if appropriate):

screen shot 2017-03-02 at 23 55 25

### CODE REVIEW

**Comment by jbpros** [comment]
There is http://cucumber.github.io/cucumber-js/ already. Would it be better to start from there instead of starting from scratch to reach the additional learning objectives (cues, guidance, ...)?

**Comment by aslakhellesoy** [comment]
Can you point me to the source for that @jbpros?

**Comment by jbpros** [comment]
Sure: https://github.com/cucumber/cucumber-js/tree/gh-pages

**Comment by mattwynne** [comment]
+1 to building upon http://cucumber.github.io/cucumber-js/ - it's an awesome piece of work.

**Pull request closed without merging**
