### PR TITLE
fix cucumber-expressions tests

### LINKED ISSUE #358: Distinguish between "no match" and "match with no groups"
I could be wrong, but it seems to me that there is no distinction between "no match":

https://github.com/cucumber/cucumber/blob/662b3662422c5301f685999704d9dd38e6341757/cucumber-expressions/go/regular_expression_test.go#L45-L47

And when there is a match with no groups:

https://github.com/cucumber/cucumber/blob/662b3662422c5301f685999704d9dd38e6341757/cucumber-expressions/go/regular_expression_test.go#L61-L63

The other implementations return `null` for the former and `[]` for the latter. How will Cucumber know which case it is if we always get `[]`?

### PR DESCRIPTION
**Pull request by charlierudolph**
resolves #358

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
LGTM!

I recommend [tbd](https://trunkbaseddevelopment.com) for small stuff like this. Less process/communication overhead.

**Comment by aslakhellesoy** [comment]
You would have made those commits on master, pushed, and not sent a PR :-)

**Comment by charlierudolph** [comment]
Auhh. Ok.

**Comment by aslakhellesoy** [comment]
http://www.davefarley.net/?p=247 :-)

**Comment by charlierudolph** [comment]
Very interesting. I like feature branches for the code reviews (haven't done much pair programming) and the fact that you can count on CI to run the tests to ensure the build passes instead of entrusting the dev to run all the tests. In cases, I do think this slows things down as running the tests locally would have been faster but letting CI run the tests allows me to move onto the next task and fix up things later if need be.

A failing master typically is fast to fix, and I guess the code review could be replaced by communication earlier about how to solve the problem. I feel code reviews are also a great learning opportunity but that could be done after the code is merged where the code is inspected and asked to be cleaned up. The PR does make it more individualistic where one person is responsible for the code instead of the entire team being responsible. 

I'm undecided on this and will need to think it more.

**Pull request merged**
