### PR TITLE
Italian translation for Rule keyword and for Feature synonym keywords

### PR DESCRIPTION
**Pull request by mgiustiniani**
## Summary

Translated Keywords

## Motivation and Context

Translations missing

## How Has This Been Tested?

It hasn't.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue).

### CODE REVIEW

**Comment by mpkorstanje** [comment]
@ehuelsmann ?
```
9 distributions installed
touch .cpanfile_dependencies
perl helper-scripts/build_languages.pl < gherkin-languages.json > lib/Gherkin/Generated/Languages.pm
Can't locate Cpanel/JSON/XS.pm in @INC (you may need to install the Cpanel::JSON::XS module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at helper-scripts/build_languages.pl line 6.
```

**Comment by ehuelsmann** [comment]
@mpkorstanje: there's a fix for that in PR #1316. I was waiting to allow review on it, but since this change depends on it, I'll merge. It'll show correctness of the PR.

**Comment by mpkorstanje** [comment]
@mgiustiniani looks good. Please add an entry under the **Fixed** header and your name at the bottom of the file.

https://github.com/cucumber/cucumber/blob/master/gherkin/CHANGELOG.md

**Comment by mgiustiniani** [comment]
hi @mpkorstanje, i added changelog info to PR

**Comment by aslakhellesoy** [comment]
Hi @mgiustiniani,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by mpkorstanje** [comment]
Cheers!

**Pull request merged**
