### PR TITLE
Techniques Page - 3 amigos

### PR DESCRIPTION
**Pull request by siwood**
Added Techniques page and drafted 3 amigos section

### CODE REVIEW

**Comment by mattwynne** [comment]
Looks like good useful content to me, and it's clearly written. Is this original @siwood, not lifted from the old wiki or somewhere?

I'm a bit confused why this PR contains both the 3-amigos content in the `techniques.md` page, but also the stuff about scenario outlines in `gherkin.md`. Is there a reason for both changes to be in the same PR?

**Comment by jbpros** [comment]
Thank you @siwood. This has been merged in master as commit b3cf061.

**Comment by mattwynne** [comment]
I can't see this content at http://docs.cucumber.io - does it need some GitBook-fu to add it to the nav?

**Comment by aslakhellesoy** [comment]
I have left a comment over at http://docs.cucumber.io/docs/techniques.html - GitBook allows discussions in the documentation itself. Let's continue the discussion there to see how it works for us!

You can see open discussions over at https://www.gitbook.com/book/cucumber/cucumber/discussions

**Pull request closed without merging**
