### PR TITLE
account for example value with $

### LINKED ISSUE #374: `$` in example table not escaped correctly
## Summary
Given the following gherkin:
```gherkin
Scenario Outline:
  Given <x>

  Examples: 
    | x  |
    | $$ |
```
The step becomes `Given $` instead of `Given $$`.

## Possible Solution

I believe the problem is in the pickle generation [here](https://github.com/cucumber/cucumber/blob/b584f84e6f750fdc3bd9e47476ebfdead798c0ba/gherkin/javascript/lib/gherkin/pickles/compiler.js#L119) as the `$` is a special character in [replacement strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter).

See https://github.com/cucumber/cucumber-js/issues/1077 for the original issue

### PR DESCRIPTION
**Pull request by charlierudolph**
## Summary

resolves #374

I'm uncertain if other languages require updates for this. I'll update them if the build fails.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [x] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by charlierudolph** [comment]
@aslakhellesoy It doesn't appear any of the new tests ran on CI. Does the rsync need to happen on this PR? I had put these in the `gherkin/javascript/test-data` folder initially to run the tests locally but moved them to top level.

**Comment by aslakhellesoy** [comment]
Oh I see. Sorry, should have checked that better. Merge with master, then try this:

```
# Sync testdata to all gherkin impls
source scripts/functions.sh && rsync_files
```

And then run the entire build on Docker:

```
./scripts/docker-run Dockerfile.cucumber-build make
```

**Comment by charlierudolph** [comment]
I wanted to sync the files in this PR, so I know if any other language needs fixes.

**Comment by aslakhellesoy** [comment]
I've got a fix incoming...

**Comment by aslakhellesoy** [comment]
Ok, so e482ef9 syncs your changes to all implementations. The build passed locally. If Travis is happy we can merge.

**Pull request merged**
