### PR TITLE
[html-formatter] Use ESLint

### PR DESCRIPTION
**Pull request by aslakhellesoy**
This PR sets up [ESLint](http://eslint.org/) for html-formatter

### CODE REVIEW

**Comment by mattwynne** [comment]
@aslakhellesoy are we using labels or issue name prefixes to separate these issues out? When I get an email notification I can't see tags, so I'd like to stick to using prefixes if that's OK with the rest of us?

**Comment by aslakhellesoy** [comment]
I think we should use both, because:

* prefix, because what you said
* label, because it makes triage and filtering using the github UI a lot easier

New contributors are likely to not set any of them, so contributors should go in and add prefixes and labels when they are missing.

**Comment by aslakhellesoy** [comment]
I also use prefixes in commit messages (except when I forget!)

**Comment by mattwynne** [comment]
Sounds good.

**Pull request merged**
