### PR TITLE
Docs/Readme - Add wikipedia link for BDD

### PR DESCRIPTION
**Pull request by vcavallo**
I'm not sure if there's a subrepo for the readme - it doesn't seem like it. Let me know if I should rename this PR.

## Summary

I propose using the Wikipedia entry on BDD for the currently dead-end link in the readme.

## Motivation and Context

Fixes https://github.com/cucumber/cucumber/issues/44

## How Has This Been Tested?

Clicked the link in the readme and verified it goes to wikipedia ;)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [x] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by vcavallo** [comment]
@mlvandijk yea there are tons of books, articles and authors I'd prefer over the wikipedia page, but I figured it would be the least incendiary and closest to neutral for a start :)

**Comment by mlvandijk** [comment]
@vcavallo Agreed :) 

What do you think about either: 
* linking to this blog instead: https://cucumber.io/blog/2017/05/15/intro-to-bdd-and-tdd or
* having our own document(s) about BDD  / TDD as proposed here: https://github.com/cucumber/cucumber/pull/50 (actual PR needs some edits as there are some typos).

Note: there is a separate repo for docs: https://github.com/cucumber/docs.cucumber.io
Contributions welcome ;)

**Comment by vcavallo** [comment]
@mlvandijk As for your two options, I think the second would ultimately be best - but it's not quite ready yet, right? Since the first option is a link that is owned by cucumber, quite recent and _not-wikipedia_, I agree that would be better for now until more documents are ready (as in https://github.com/cucumber/cucumber/pull/50 like you said).
Updated README commit getting pushed after I save this comment :)

**Comment by mlvandijk** [comment]
@vcavallo Thanks! Note: I'm not anti-wikipedia perse, just wasn't impressed by this particular article ;)
Also, please feel very welcome to help on the documentation in cucumber/docs.cucumber.io!

I'm gonna go ahead and merge this; if anyone prefers a different link to BDD, please -> cucumber/docs.cucumber.io :)

**Comment by aslakhellesoy** [comment]
Hi @vcavallo,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
