### PR TITLE
Adding Scenario Outline section to Gherkin page and updating tag on SUMMARY.md

### PR DESCRIPTION
**Pull request by siwood**
Scenario Outline section is taken from https://github.com/cucumber/cucumber/wiki/Scenario-Outlines and pages 74-75 of The Cucumber Book.

### CODE REVIEW

**Comment by jbpros** [comment]
Thank you @siwood! I'd like to see more content about Gherkin being merged before the Scenario Outline gets in (I'm thinking about #34). 

Let's keep this one open in the meanwhile.

**Comment by mattwynne** [comment]
@jbpros #34 seems to be stuck in a bit of a tangled mess. Why don't we merge this one - I think @siwood's copy about scenario outlines is good quality - and then fill out the gaps after that?

I know you don't like scenario outlines @jbpros but don't let your personal biases get in the way! ;)

**Comment by jbpros** [comment]
This is good quality indeed, let's merge it and add gherkin basics.

**Comment by mattwynne** [comment]
@jbpros and I reviewed this together today. What we like:

- it's original and well-written content
- the commits are granular, and clearly commented

Thanks @siwood - we're going to give you commit access, so you can make your contributions directly into this repo in future, as well as help reviewing and merging other people's contributions.

**Comment by siwood** [comment]
@mattwynne @jbpros Thank you! I am still figuring out git so I may ask some questions along the way.

**Pull request merged**
