### PR TITLE
Json schema for message protocol

### PR DESCRIPTION
**Pull request by aslakhellesoy**
This is a Draft PR to replace protobuf with pure JSON and JSON Schema, addressing #1386.

TODO:

* [x] TypeScript: Modify ts code generator to define a `Status` alternate type from the enum in the schema. Same for `ContentEncoding`
* [ ] Working PR for [cucumber-js](https://github.com/cucumber/cucumber-js/pull/1645)
* [ ] Working PR for cucumber-ruby
* [ ] Working PR for cucumber-jvm

Later:

* [ ] Validate all generated messages in compatibility kit with the JSON schema.
* [ ] Elixir implementation/code generator
* [ ] .NET implementation/code generator
* [x] Go implementation/code generator

We can live with a combination of protobuf/json schema implementations for some time, as long as we keep them in sync. The gherkin acceptance tests will catch any inconsistencies.

### CODE REVIEW

**Comment by WannesFransen1994** [comment]
Not sure if it's relevant, but following libraries might be helpful for the Elixir code generation:

* [https://hex.pm/packages/ex_json_schema](https://hex.pm/packages/ex_json_schema)
* [https://hex.pm/packages/json_schema](https://hex.pm/packages/json_schema)
* [https://hex.pm/packages/typed_struct](https://hex.pm/packages/typed_struct)

**Comment by aslakhellesoy** [comment]
Thanks @WannesFransen1994 we'll have a look at those.

**Comment by mpkorstanje** [comment]
For java we should make sure the compiler preserves the parameter names. This will help various object mappers figure things out.

```xml

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.8.1</version>
                    <configuration>
                        <parameters>true</parameters>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
```

**Comment by mpkorstanje** [comment]
For java we should also get rid of Jackson. Even shaded it will trigger a frequent release cycle due to security findings.

**Comment by aslakhellesoy** [comment]
What do you recommend we use instead of Jackson @mpkorstanje?

We need to be able to serialise POJOs to JSON. I don't think we need deserialisation.

**Comment by aslakhellesoy** [comment]
ping @mpkorstanje - what do you think we should use instead of jackson?

We definitely need a library that can serialise objects to JSON.

I don't think we need deserialisation, so we could use a simple library that only does serialisation. I've looked at https://github.com/fabienrenaud/java-json-benchmark, and not a single one of them has serialisation only (which increases the attack-vector surface).

Shall we just go with a shaded `com.eclipsesource.minimal-json` as we use in `create-meta`?

**Comment by mpkorstanje** [comment]
You want to turn abitrary POJOs into json right? `minimal-json` only supports turning json objects into json.

**Comment by aslakhellesoy** [comment]
> You want to turn abitrary POJOs into json right? minimal-json only supports turning json objects into json.

Ah yes, forgot about that. Yes, we need to turn POJOs into JSON.

**Comment by mattwynne** [comment]
@aslakhellesoy after the discussions today with @gasparnagy at the committers' Zoom, it struck me that it might be a good idea to write an [ADR](https://github.com/npryce/adr-tools) as part of this PR. I'd be happy to write a draft if you like, or we could pair/ensemble on it?

**Comment by aslakhellesoy** [comment]
> @aslakhellesoy after the discussions today with @gasparnagy at the committers' Zoom, it struck me that it might be a good idea to write an [ADR](https://github.com/npryce/adr-tools) as part of this PR. I'd be happy to write a draft if you like, or we could pair/ensemble on it?

Yes, an ADR would be great @mattwynne!

**Comment by aurelien-reeves** [comment]
The removal of "sudo" before installing npm globally was the thing to fix the CI? 😨

This is a big PR to review. Here's a big list of question 😅

- What should we focus on while reviewing?
- What are the next steps?  
- When could it be merged? 
- Should we wait for the PR in cucumber-js, cucumber-ruby and cucumber-jvm to be ready too? 
- Should we wait for .Net and Elixir to be implemented?

**Comment by aslakhellesoy** [comment]
> The removal of "sudo" before installing npm globally was the thing to fix the CI? 😨
> 
> This is a big PR to review. Here's a big list of question 😅
> 
> * What should we focus on while reviewing?

Primarily finding breaking changes in APIs and data structures

> * What are the next steps?

Merge to master and continue working on Cucumber PRs

> * When could it be merged?

I think we can merge now, unless there are objections.

> * Should we wait for the PR in cucumber-js, cucumber-ruby and cucumber-jvm to be ready too?

I think we can work on those after this is merged.

> * Should we wait for .Net and Elixir to be implemented?

And Perl. I think we should disable them all (they already are). Waiting for them will cause too much delay. They can catch up at their own pace. We should create an issue for all 3 of them.

**Review by davidjgoss — APPROVED** [review]

**Pull request merged**
