### PR TITLE
Pin dependencies in mono-repo

### PR DESCRIPTION
**Pull request by vincent-psarga**
## Summary

This follows a discussion we had yesterday over the weekly commiters meeting.
The idea is to pin down the dependencies (so not excluding `Gemfile.lock` for example) so we don't get unexpected failures due to a new release of a dependency.

A new nightly build is executed with the dependencies unpinned, so we get notified if a new release of a dependency will cause problems.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] The change has been ported to Java.
- [x] The change has been ported to Ruby.
- [ ] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the CHANGELOG accordingly.

### CODE REVIEW

**Comment by mpkorstanje** [comment]
```
make[2]: Entering directory '/home/cukebot/cucumber/c21e/ruby'
touch .deps
bundle exec rspec --color
bundler: command not found: rspec
Install missing gem executables with `bundle install`
```

What's that about?

**Comment by aslakhellesoy** [comment]
> ```
> make[2]: Entering directory '/home/cukebot/cucumber/c21e/ruby'
> touch .deps
> bundle exec rspec --color
> bundler: command not found: rspec
> Install missing gem executables with `bundle install`
> ```
> 
> What's that about?

Try this instead:

```
```

> ```
> make[2]: Entering directory '/home/cukebot/cucumber/c21e/ruby'
> touch .deps
> bundle exec rspec --color
> bundler: command not found: rspec
> Install missing gem executables with `bundle install`
> ```
> 
> What's that about?

Where does the `touch .deps` come from?

**Comment by mpkorstanje** [comment]
It's from the failing build.

**Comment by aslakhellesoy** [comment]
Obsolete now :-(

**Pull request closed without merging**
