### PR TITLE
add test step keys to attachment message

### PR DESCRIPTION
**Pull request by charlierudolph**
## Summary

While updating cucumber-js to use latest gherkin / cucumber-messages, this is one message cucumber-js used that is not currently available. The attachment message would either have source or the testStepId / testCaseStartedId.

## Details

Cucumber-js previously fired an event like this when you attached something in a hook or step.
I can get this applied to all cucumber-messages languages once we agree on the changes.

## Motivation and Context

This is one way users get data to be saved into the json formatter (and now the protobuf formatter). 

## How Has This Been Tested?

No tests currently, once deployed, cucumber-js will depend on these changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [ ] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Yes, this looks good to me.

My thinking is that attachments representing syntax errors (parse time) are linked to the source, while runtime attachments are attached to a test step for a particular test run.

I’d also like to deprecate the use of `SourceReference source` and replace it with a `string sourceId`.

Can we add that in this PR?

/cc @vincent-psarga - this may affect the json formatter?

**Comment by charlierudolph** [comment]
Hmm. For `sourceId` do you think its worth adding an id to the `Source` message or just making the field `sourceUri`?

**Comment by vincent-psarga** [comment]
@aslakhellesoy this should not impact the JSON formatter from what I see.

That said, I'm wondering about the way the "link" is done. I think having a field:

```
message TestStep {
  // same than previously
  repeated string attachementIds = 6;
```

would be more consistent with the other links.

**Comment by aslakhellesoy** [comment]
> @aslakhellesoy this should not impact the JSON formatter from what I see.
> 
> That said, I'm wondering about the way the "link" is done. I think having a field:
> 
> ```
> message TestStep {
>   // same than previously
>   repeated string attachementIds = 6;
> ```
> 
> would be more consistent with the other links.

That's not possible. The execution `Attachment` messages are created after the `TestStep` message. For example when a screenshot is attached during an `After` or `AfterStep` hook.

**Comment by aslakhellesoy** [comment]
I've given this a bit more thought, and I think it's OK to keep the `source` reference as-is, so I'll merge this without any further changes.

**Comment by vincent-psarga** [comment]
> That's not possible. The execution `Attachment` messages are created after the `TestStep` message. For example when a screenshot is attached during an `After` or `AfterStep` hook.

Indeed, I had not thought of that. Why not in the `TestStepFinished` message then ?

**Comment by aslakhellesoy** [comment]
> > That's not possible. The execution `Attachment` messages are created after the `TestStep` message. For example when a screenshot is attached during an `After` or `AfterStep` hook.
> 
> Indeed, I had not thought of that. Why not in the `TestStepFinished` message then ?

Because messages should be atomic. I think you are suggesting that in order to send screenshots we have to:

1) Send an `Attachment` message (which isn't linked to anything)
2) Keep track of all the sent `Attachment` messages and add their ids to `sourceIds` in a later `TestStepFinished` message.

If either of those messages are skipped we'd have a system in a strange state.

**Comment by vincent-psarga** [comment]
Ok that makes sense now.

I was just a bit doubtful with the composite key to reference the test step (`TestCaseStartedId` + `TestStepId`), but in fact that already what we have for `TestStepStarted` and `TestCaseFinished` messages.

**Comment by charlierudolph** [comment]
Note. I think we will need json formatter updates after this goes in. Cucumber ruby and js have the attachments in the produced json: https://github.com/cucumber/cucumber-ruby/blob/master/features/docs/formatters/json_formatter.feature#L285

**Pull request merged**
