### PR TITLE
Add cucumber-support-code library

### PR DESCRIPTION
**Pull request by vincent-psarga**
## Summary

The idea is to have a library in the mono-repo responsible for:
 - storing the `Hooks` and `StepDefinitions`
 - making the `matches` (with either `cucumber-expressions` or `cucumber-tag-expressions`
 - executing the support code
 - generating the correct messages

And ideally (in the future), use them in the cucumber implementations.

For now it's mainly a draft with parts stolen from `fake-cucumber`.

## Motivation and Context

Have the "same" implementation of handling hooks/step definitions in all cucumbers.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [ ] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
This is extracted from fake-cucumber isn't it? I am concerned that extracting this now while fake-cucumber is very much in flux might make it more cumbersome to make changes to fake cucumber as well as this proposed new library.

Why do you want to extract this now?

**Comment by vincent-psarga** [comment]
You're right, extraction is a bit early (tough it helped a bit to avoid name collision).
I'll move that to a folder inside fake-cucumber and we'll see once it's stable enough to have it in its own library.

The idea behind extracting it was to ease porting to other languages (as it mainly takes messages as input/ouput), but that's premature.

**Comment by vincent-psarga** [comment]
So, the code about support-code has been moved the `fake-cucumber/support-code`.
I've done my best to use it like an external library (so not including from the files inside the folder but from the `index.ts` file).
I've also rewritten some of the code and moved it to `fake-cucumber/test-case-builder` with the same idea (although I wasn't able to include files the same way :/ )

In the "not-supported-anymore-but-I-will-fix-that" part, I need to implement again calculating the Duration in `fake-cucumber/test-case-builder/TestStep#execute`.

Also, I think the code is more readable and it has  a better separation of concern. That said, the way `Cucumber` and `CucumberStream` are called are not good (the `supportCodeRegister` argument is awful ...)

Ah and there's lot of code that could be removed now (like TestStep, TestCase etc that is not below `test-case-builder`)

**Comment by aslakhellesoy** [comment]
Let's hold iff merging this until after https://github.com/cucumber/cucumber/pull/817 is merged, as it has changes to fake-cucumber too.

**Comment by vincent-psarga** [comment]
> Let's hold iff merging this until after #817 is merged, as it has changes to fake-cucumber too.

Agree :)

And also it breaks the `json-formatter` build so I guess I forgot some messages (that's why I started adding the `golden` part in the `Makefile`)

**Pull request closed without merging**
