### PR TITLE
gherkin / languages : translate Rule to Czech Pravidlo in gherkin-languages.json

### PR DESCRIPTION
**Pull request by plavcik**
## Summary

translated Rule to Czech Pravidlo in gherkin-languages.json

## Details

gherkin-languages.json adjusted

### CODE REVIEW

**Comment by aurelien-reeves** [comment]
Thanks for your contribution @plavcik!

Could you please distribute the changes to the different parser implementations?

To do so, from within the docker image (`make docker-run`), in `/app/gherkin`:
```
source ../scripts/functions.sh
rsync_files
make clean
make
```

That should sync `gherkin-languages.json` in the different implementations and then fix the CI

**Comment by plavcik** [comment]
> 
> That should sync `gherkin-languages.json` in the different implementations and then fix the CI

Getting error in part `make`. Will return to it later.

```
> @cucumber/gherkin@18.0.0 test
> mocha

sh: 1: mocha: not found
npm ERR! code 127
npm ERR! path /app/gherkin/javascript
npm ERR! command failed
npm ERR! command sh -c mocha
```

**Review by mpkorstanje — APPROVED** [review]

**Review by mpkorstanje — CHANGES_REQUESTED** [review]
LGTM but please add an entry under the "Fixed" header:

https://github.com/cucumber/cucumber/blob/master/gherkin/CHANGELOG.md

**Comment by plavcik** [comment]
> LGTM but please add an entry under the "Fixed" header:
> 
> https://github.com/cucumber/cucumber/blob/master/gherkin/CHANGELOG.md

Not sure, what to put there. Could you help me?

**Comment by aslakhellesoy** [comment]
Hi @plavcik,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
