### PR TITLE
Finishing .NET Parser after .NET Core merge and monorepo

### PR DESCRIPTION
**Pull request by SabotageAndi**
## Summary
This PR makes the last changes to finish the work on .NET Core support for the .NET parser.

## Details
Most stuff is about:
- for releasing/creating NuGet packages.
- finalizing build configuration for AppVeyor & Travis => this needs still some work, thats the reason why the PR is work in progress.

## Motivation and Context
Finish the work that was started in https://github.com/cucumber/gherkin/pull/215

## How Has This Been Tested?
By the Unit Tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] I've added tests for my code.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by SabotageAndi** [comment]
@aslakhellesoy Is there a reason why no builds were triggered for this PR?

**Comment by aslakhellesoy** [comment]
I'm sure there is a reason, but I don't know what it is.

All PRs should trigger a build. I need to look into it.

**Comment by aslakhellesoy** [comment]
Hey @SabotageAndi I just enabled Travis builds for PR updates, which is off by default. If you push another commit, the build should run.

However, the build won't actually build and run Gherkin.NET yet, see #177. I'll have to check it manually, but that's OK for now.

**Comment by SabotageAndi** [comment]
@aslakhellesoy What's about the appveyor builds? I am more interested in them, because they build on Windows where we can compile for .NET 4.5 and .NET Core.

**Comment by aslakhellesoy** [comment]
Appveyor builds have not been set up for the monorepo yet. Fancy sending a PR for that?

**Comment by SabotageAndi** [comment]
@aslakhellesoy as there is now an appveyor build (https://ci.appveyor.com/project/aslakhellesoy/gherkin), could you enable it for PRs?

**Comment by jmezach** [comment]
With .NET Core 2.0 release today, any chance we can get this done soon?

**Comment by aslakhellesoy** [comment]
Hi @SabotageAndi,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by aslakhellesoy** [comment]
Ah - the commitbit bot is working :-) (yes, I know this isn't your first contribution - it only looks if you're already in the `committers` team)

@SabotageAndi I merged this to master and pushed to the [subrepo](https://github.com/cucumber/gherkin-dotnet), but the [Appveyor build](https://ci.appveyor.com/project/aslakhellesoy/gherkin/build/1.0.175) is failing. Any idea?

**Comment by SabotageAndi** [comment]
Looks like AppVeyor already updated to .NET Core 2.0. The PR was made when 1.1 was the latest.
I will have a look and send a new PR with fixes.

**Pull request merged**
