### PR TITLE
cucumber-expressions: Bugfix for nested capture groups. Ref #375

### PR DESCRIPTION
**Pull request by aslakhellesoy**
Fix for #375.

* [x] Go
* [x] Java
* [x] JavaScript
* [x] Ruby

@charlierudolph - could you port this to Go please? I tried and failed - my go chops aren't strong enough yet :-)

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
@charlierudolph I'd like to make a release with this fix. Any chance you could update the go impl?

**Comment by charlierudolph** [comment]
Sure. I should be able to do this tonight

**Comment by charlierudolph** [comment]
@aslakhellesoy the go version is updated and I removed a TODO so now it is more consistent with the other implementations

**Comment by xtrasimplicity** [comment]
Brilliant. Great work, @charlierudolph! :)

**Pull request merged**
