### PR TITLE
html-formatter: add cucumber icon to page

### PR DESCRIPTION
**Pull request by davidjgoss**
## Summary

A trivial thing, but maybe a nice touch. Supported in all modern browsers, using an SVG of the official Cucumber logo.

## Screenshots (if appropriate):

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [ ] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have updated the CHANGELOG accordingly.

### CODE REVIEW

**Review by aslakhellesoy — COMMENTED** [review]
I wonder if we should use the official Cucumber SVG logo rather than an emoji?

**Comment by davidjgoss** [comment]
@aslakhellesoy good point, done

**Comment by davidjgoss** [comment]
> This reminds me that we have a slightly updated logo since Cucumber became part of SmartBear.

Ah okay - I pulled this one from the header in https://cucumber.io/, didn't realised there was another iteration.

**Comment by aslakhellesoy** [comment]
Never mind - you picked the right logo. Let's merge this!

**Pull request merged**
