### PR TITLE
[WIP] OCaml messages

### PR DESCRIPTION
**Pull request by cyocum**
## Summary

This PR represents the OCaml version of the messages for use with Cucumber.ml

## Details

* The changes the message.proto file due to a [bug](https://github.com/mransan/ocaml-protoc/issues/129) in `ocaml-protoc`.
* Adds the `dune` build information to compile message.proto file
* Adds Opam information for if/when this gets added to Opam

## Motivation and Context

This allows Cucumber.ml to use the new gherkin-go implementation for Gherkin 6.0

## How Has This Been Tested?

This needs to be integrated with the new Cucumber.ml structure so it has not yet been used and tested

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
TODO:

- [ ] Add `ocaml`, `opam` and `dune` to `/Dockerfile.cucumber-build` (so the monorepo build can pass)
- [ ] Add `.travis.yml` that runs `make default`
- [ ] Add `Makefile` with `default` and `clean` targets
- [ ] Add `Makefile` targets for publishing `opam` package
- [ ] Add a simple unit test for writing/reading a message

**Comment by cyocum** [comment]
Sadly,  I have not had much time to work on this in the past few months.  I need someone to hand hold me through this because I am, at this point, completely confused as to how this is supposed to work.  I am not sure it is even possible? I don't know.

**Comment by aslakhellesoy** [comment]
Hi @cyocum do you still intend to finish this? We're introducing a new bug triage process, so I'll close this soon unless it gets picked up.

See https://github.com/cucumber/cucumber/pull/1326/files for details

**Comment by aslakhellesoy** [comment]
This is obsolete and not prioritised because of #1414

**Pull request closed without merging**
