### PR TITLE
Elixir gherkin parser implementation

### PR DESCRIPTION
**Pull request by WannesFransen1994**
Elixir gherkin parser implementation.

Work in progress. TODO list:

* [x] Refactor tests so that all the test run despite one failure. Also provide a nice "report" / output
* [x] Refactor project name
* [x] Integrate with monorepo (makefile ) structure
* [x] CICD integration
* [x] rsync integration (also for messages?)
* [x] Request review
* [x] Update github link in mix.exs
* [x] Update documentation (generated docs + quick overview readme.md)

### CODE REVIEW

**Comment by mpkorstanje** [comment]
I've renamed the issue to be a bit more descriptive of what its about.

**Comment by marnen** [comment]
Cool. Are you aware of https://github.com/meadery/white-bread (which is looking for a maintainer)?

**Comment by WannesFransen1994** [comment]
Yes, though my goal (for now) was to create a completely conform implementation which can be easily maintained regardless of language. Hence the start with the messages library and the gherkin parser which uses berp for the grammar rules.

No doubt though that this library, together with https://github.com/cabbage-ex/cabbage, https://github.com/hauleth/watermelon and https://github.com/Ajwah/ex_cucumber/tree/master/apps/cucumber_expressions can be used to create an implementation that could be merged into the cucumber monorepo.
`
Though really, this is just a Gherkin parser. My goal was to create a parser which can be maintained by the cucumber community for people who decide to create a cucumber implementation for Elixir :)

**Comment by WannesFransen1994** [comment]
I've added the makefile. Would you mind verifying this please @aslakhellesoy ? Thank you.

**Comment by WannesFransen1994** [comment]
Update TODO list:
* [ ] rename project to `cucumber_gherkin`

**Comment by aslakhellesoy** [comment]
It's landed! https://hex.pm/packages/cucumber_gherkin

Thanks a lot @WannesFransen1994 💯

**Comment by alvivi** [comment]
I'm not sure if this is a good place to talk about this (or maybe opening an issue), but this library cannot be used directly from Hex because the `resources/gherkin_languages.json` file is not packed together with the library.  I think that you need to add it to `files` field in the `mix.exs`'s `package` section.

Happy to see this :) For now I will continue to use the old elixir parser

**Pull request merged**
