### PR TITLE
Update gherkin-languages.json

### PR DESCRIPTION
**Pull request by stevenhuijgens**
Extended dutch 'then' to improve on grammar

## Summary
Extended dutch 'then' to improve on grammar

## Motivation and Context
Steps as 'Given / When / Then / And the window is opened and active' translate into 'Gegeven / Als / Dan / En het venster actief en geopend is'. 'Dan' should be extended to increase readability. 'Verwacht dat / Valideer dat het venster actief en geopend is' is correct.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mlvandijk** [comment]
Thoughts @mpkorstanje?

**Comment by mpkorstanje** [comment]
Both `Verwacht` and `Valideer` describe actions, not state. Translated to English it would equivalent to adding `Expect` and `Assert that` which is test-language, not scenario language.

I think the problem 

The example could be rewritten to

```
Dan is het venster actief en geopend
```

**Comment by aslakhellesoy** [comment]
When and Then are temporal adverbs. Translations should be too (at least for indo-european languages, with similar grammar).

This proposal doesn’t sound right to me.

**Comment by mlvandijk** [comment]
Agreed with @mpkorstanje and @aslakhellesoy

**Comment by aslakhellesoy** [comment]
Thanks for your contribution @stevenhuigens - we’re not going to accept this, as it diverges too much from the established language.

**Pull request closed without merging**
