### PR TITLE
create-meta/java: handle null values in ci dict

### LINKED ISSUE #1228: Create-Meta: Java Implementation cannot handle CIs with `null` in ciDict
When trying to create a Meta message with the java implementation, I get an NPE when trying to whenever in ciDict one of the message fields is defined as `null`. e.g. running 
~~~
 "CodeShip": {
    "url": "${CF_BUILD_URL}",
    "git": {
      "remote": "${CF_COMMIT_URL}",
      "revision": "${CF_REVISION}",
      "branch": "${CF_BRANCH}",
      "tag": null
    }
  },
~~~

The ruby and js implementations work fine, but for java running cucumber (via JUnitRunner) with the environment variable CF_BUILD_URL set, leads to an NPE:
~~~
Exception in thread "main" java.lang.UnsupportedOperationException: Not a string: null
        at com.eclipsesource.json.JsonValue.asString(JsonValue.java:384)
        at com.eclipsesource.json.JsonObject.getString(JsonObject.java:674)
        at io.cucumber.createmeta.CreateMeta.createCi(CreateMeta.java:90)
        at io.cucumber.createmeta.CreateMeta.detectCI(CreateMeta.java:75)
        at io.cucumber.createmeta.Main.main(Main.java:21)
~~~

## Your Environment

* Version used: cucumber 6.8.1, create-meta 2.0.2
* Operating System and version: Windows 10

### PR DESCRIPTION
**Pull request by kgeilmann**
This fixes #1228 by handling null explicitly.

I'm unsure, if it would be worth to add acceptance tests for all available CIs.

### CODE REVIEW

**Review by mpkorstanje — APPROVED** [review]
Looking good!

**Comment by mpkorstanje** [comment]
> I'm unsure, if it would be worth to add acceptance tests for all available CIs.

That doesn't scale. It's usually better to do this per property. However in this case nearly all properties are nullable.

**Comment by aslakhellesoy** [comment]
Hi @kgeilmann,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by mpkorstanje** [comment]
Cheers!

Should be released with `cucumber-jvm:6.8.2`.

**Pull request merged**
