### PR TITLE
DOC: Installation page additions

### PR DESCRIPTION
**Pull request by siwood**
Using installation instructions from the https://cucumber.io/docs#installation pages to add Javascript and Ruby instructions. Adding some structure to the installation part of the SUMMARY.md menu.

### CODE REVIEW

**Comment by tsundberg** [comment]
I looked at this pull request and think it can be merged without

**Comment by brasmusson** [comment]
@tsundberg The Three Amigos is already merged (https://docs.cucumber.io/docs/techniques.html#three-amigos), but habit of @siwood to merge from `cucmber:master` to the PR branch (instead of rebaseing), will make the list of commits in the PR longer than it should be.

**Comment by tsundberg** [comment]
@brasmusson what is your proposal? Merge or not merge?

**Comment by siwood** [comment]
@brasmusson I'm new to git. I will try rebasing next time to avoid the annoying extra commits. Thanks for pointing that out!

**Comment by siwood** [comment]
Ok, I think it's cleaned up.

**Pull request merged**
