### PR TITLE
Recursively build Javascript dependencies

### PR DESCRIPTION
**Pull request by vincent-psarga**
## Summary

When running `make` inside a Javascript library, it will also build the libraries inside the mono-repo on which it relies.

## Details

use the content of `.internal-dependencies` to know what to build.

## Motivation and Context

Tired of forgetting to build a dependency...

## Types of changes

- [x] Build
- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [ ] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by vincent-psarga** [comment]
Hmmm, it looks like the serial-build takes way more time than usually with this. I'll have to fix it before merging.

**Comment by aslakhellesoy** [comment]
I think the reason this takes a long time now is that you're circumventing Make's dependency resolution and reliance on the file system to decide whether or not something should be built.

**Comment by vincent-psarga** [comment]
I've updated the makefile the dependencies will not be built every time, we'll have to run `make internal-dependencies` to have the dependencies built.

I'm wondering where I could document this so it's not lost :/

**Comment by vincent-psarga** [comment]
So it's not using the `.built` file as a target to ensure building only needed dependencies. I was not able to declare the list of dependencies as a list in `Makefile`, so I used `.internal-dependencies`.

If I declare:
```
INTERNAL_DEPENDENCIES = gherkin cucumber-messages
```

in `Makefile`, it's not correctly picked as required targets in `default.mk`. If I add the same line in `default.mk`, it works fine ...
I guess I'm missing something.

**Comment by aslakhellesoy** [comment]
Did you try defining `INTERNAL_DEPENDENCIES` in the `Makefile` above the line that does `include default.mk`? That’s what we do with the `MAKEFILES` variable.

**Comment by vincent-psarga** [comment]
> Did you try defining `INTERNAL_DEPENDENCIES` in the `Makefile` above the line that does `include default.mk`? That’s what we do with the `MAKEFILES` variable.

Indeed, it's working fine now, thanks :)

**Comment by vincent-psarga** [comment]
I think we should have some discussions on how this goes forward from now on. If I apply the same system to other languages, there'll be loads of copy paste in the different `Makefile` from one language to another.

I was thinking about having a internal-dependencies` file at the library level (for example `cucumber/gherkin/internal-dependencies` would contain `cucumber-messages`) and the various makefiles in the languages repos would declare something like `INTERNAL_DEPENDENCIES=$(shell cat ../internal-dependencies)` and so avoid having to copy-paste the dependencies from one language to another). Not sure that's the best solution that said :/

**Comment by aslakhellesoy** [comment]
The `.internal-dependencies` file is now gone, and I think the new way to build a subset is sufficient. Closing this.

More details [here](https://github.com/cucumber/cucumber/blob/master/CONTRIBUTING_NEW.md#building-a-subset).

**Pull request closed without merging**
