### PR TITLE
Update Indonesian Gherkin Language

### PR DESCRIPTION
**Pull request by KniveX**
## Summary
Update Indonesian gherkin language to a more natural sentence.

## Details
- Add missing space for a `but` term
- Add 2 terms for `given`

## Motivation and Context
The current Indonesian gherkin sentence is a bit awkward when said aloud.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [ ] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [ ] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [x] My change requires a change to the documentation. (specifically: https://cucumber.io/docs/gherkin/reference/#gherkin-dialect-id-content)
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the CHANGELOG accordingly.

This is my first time creating a pull request. I apologize if I made any mistake.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Looks good to me @KniveX. We need to propagate your changes to sub  directories. Can you please run this?

```
source scripts/functions.sh && rsync_files
```

Then this:

```
./scripts/docker-run Dockerfile
cd gherkin
make
exit
```

After this you should have some more modified files on your file system. Commit these files and push to the same branch.
After this there should be a bunch

**Comment by KniveX** [comment]
Ok @aslakhellesoy, looks like the tests all passed now.

So if I edit things here, I have to run the commands again, and to make sure the check tests passed?

**Comment by aslakhellesoy** [comment]
Thanks @KniveX. Yes, we have this weird copy-files-around setup since this is a polyglot monorepo :-)

**Comment by KniveX** [comment]
Ahh, so that's what "monorepo" on the description means 😁
Anyway, thank you for your help @aslakhellesoy

**Comment by aslakhellesoy** [comment]
Hi @KniveX,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
