### PR TITLE
[WIP] Added support for BeforeStep hooks

### PR DESCRIPTION
**Pull request by almostwhitehat**
This goes along with my pull request for cucumber-ruby-core for the same functionality.
This is to add support for @BeforeStep hooks, which are executed prior to each step within a scenario.

### CODE REVIEW

**Comment by mattwynne** [comment]
Closing due to inactivity.

**Comment by dionysiaBBC** [comment]
any update on this 'adding support for @BeforeStep hooks, which are executed prior to each step within a scenario.'? are you planning to have a fix?

**Comment by dionysiaA** [comment]
any update on this ' adding support for @BeforeStep hooks, which are executed prior to each step within a scenario.'? Are you planning to have a fix?

**Comment by mattwynne** [comment]
We need a pull request. Would you like to help put one together @dionysiaA?

**Comment by aesnyder** [comment]
This would be really helpful for us at the moment.

I understand this is closed due to inactivity. I'm happy to help get this across the line. What is left to be completed? 

@almostwhitehat @mattwynne

**Comment by mattwynne** [comment]
For the record, I helped @aesnyder use the [events API](http://www.rubydoc.info/github/cucumber/cucumber-ruby/Cucumber/Events) to do this via a gitter chat.

**Comment by aesnyder** [comment]
yep - and it worked flawlessly! thanks you so much @mattwynne

**Pull request closed without merging**
