### PR TITLE
gherkin/c: change tests from post build step to tests.

### PR DESCRIPTION
**Pull request by DewJunkie**
run tests post build so build will fail if tests fail.

## Summary

Tests are implemented as a post build step.  Determining what failed is hard when used in this manner.  Tests should be added as ctest tests, which is the norm for cmake.

## Details

Moved tests into add_test
run all tests as a post build step.  **Build will still fail if tests fail**

Output on build if there is a failing tests is now
```
  37/37 Test #37: /testdata/good/very_long.feature ......................................   Passed    4.30 sec

  92% tests passed, 3 tests failed out of 37

  Total Test time (real) =   5.96 sec

  The following tests FAILED:
         11 - /testdata/good/i18n_emoji.feature (Failed)
         12 - /testdata/good/i18n_fr.feature (Failed)
         13 - /testdata/good/i18n_no.feature (Failed)
  Errors while running CTest
```

## Motivation and Context

Some tests fail on windows.  In the existing setup, you get a wall of text, many pages, and build failed.  After change build still fails, but much less text, and now text is useful.  Tells which test failed.

## How Has This Been Tested?

readme.md build instructions for windows 10 using msvc
- Windows currently has some failing tests.  This was existing behavior prior to patch, and out of scope for this PR.  I will make an issue to track these failures and try to fix.
```
  The following tests FAILED:
         11 - /testdata/good/i18n_emoji.feature (Failed)
         12 - /testdata/good/i18n_fr.feature (Failed)
         13 - /testdata/good/i18n_no.feature (Failed)
  Errors while running CTest
```

readme.md build instructions for ubuntu 20.04

## Types of changes
cmake generator changes, no functional changes.  Make life easier for new devs.

## Checklist:

- [ ] The change has been ported to Java.
- [ ] The change has been ported to Ruby.
- [ ] The change has been ported to JavaScript.
- [ ] The change has been ported to Go.
- [ ] The change has been ported to .NET.
- [ ] I've added tests for my code.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the CHANGELOG accordingly.

### CODE REVIEW

**Comment by DewJunkie** [comment]
Hey, if multiple PRs is bad form let me know.  If I had more history here, I may have combined all 3 of these into a Fix cmake build issues on windows.  And if that's easier when they are related and small, doesn't make a difference to me.  I was just trying to make the scope easy to understand.

**Comment by aslakhellesoy** [comment]
Hi @DewJunkie,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by DewJunkie** [comment]
Nice, thanks.  Do these automatically get pushed out to the seperate repos ie gherkin-c or is there something to be done?

**Comment by mpkorstanje** [comment]
No. It's pushed automatically on a green build.

**Pull request merged**
