### PR TITLE
[cucumber-expressions] generated expressions - expose argument names

### LINKED ISSUE #82: [cucumber-expressions] generated expressions - expose argument names
When generating step snippets, I would like the generated expression to expose the argument names, so the function arguments in the snippet use the same name.

Current test
```js
it("documents expression generation", () => {
    const transformLookup = new TransformLookup()
    /// [generate-expression]
    const generator = new CucumberExpressionGenerator(transformLookup)
    const undefinedStepText = "I have 2 cucumbers and 1.5 tomato"
    const generatedExpression = generator.generateExpression(undefinedStepText, true)
    assert.equal(generatedExpression.source, "I have {arg1:int} cucumbers and {arg2:float} tomato")
    assert.equal(generatedExpression.transforms[1].typeName, 'float')
    /// [generate-expression]
  })
```

Proposed addition to the test
```js
assert.deepEqual(generatedExpression.argumentNames, ['arg1', 'arg2'])
```

### PR DESCRIPTION
**Pull request by charlierudolph**
@aslakhellesoy 

resolves #82 
I think cucumber-expressions needs it own repo similar to gherkin so there is a single CI build to test everything.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## Checklist:

- [x] I've added tests for my code.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
> I think cucumber-expressions needs it own repo similar to gherkin so there is a single CI build to test everything.

We'll be gradually moving the entire Cucumber ecosystem into a single monorepo (this one), and have read-only manyrepos, one for each language. The cucumber-expressions library already has manyrepos:

* https://github.com/cucumber/cucumber-expressions-java
* https://github.com/cucumber/cucumber-expressions-javascript
* https://github.com/cucumber/cucumber-expressions-ruby

This is currently synced manually by me using a script called [push-subtrees](https://github.com/cucumber/cucumber/blob/master/push-subtrees). I want to automate this as part of CI, but haven't gotten around to it yet. FYI this script uses a tool called [splitsh-lite](https://github.com/splitsh/lite)

**Comment by charlierudolph** [comment]
K. My main concern was when I create a PR here, I'd like a CI build for each of the subtrees I touch.

**Comment by aslakhellesoy** [comment]
Yes I would love for that to happen, but it's tricky to set up.

**Comment by aslakhellesoy** [comment]
@charlierudolph I've requested some help with this in splitsh/lite#24

**Comment by charlierudolph** [comment]
awesome!

**Pull request merged**
