### PR TITLE
Swedish translation for the "Rule" keyword

### PR DESCRIPTION
**Pull request by johnknoop**
## Summary

Just translated a keyword.

## Motivation and Context

The word wasn't translated before.

## How Has This Been Tested?

It hasn't.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).

### CODE REVIEW

**Comment by luke-hill** [comment]
See https://github.com/cucumber/cucumber/blob/master/gherkin/CHANGELOG.md#changed-5 for examples of how others have done it.

> Fixed Estonian translation of "Rule" (#973 [ookull])
Fixed Estonian translation of "Scenario Outline" (#972 [ookull])

**Comment by johnknoop** [comment]
@luke-hill thanks. Looks like no changes to the changelog is needed then.

Any idea what might be wrong with the CI build?

**Comment by aslakhellesoy** [comment]
Takk @johnknoop - the build error [describes what to do](https://app.circleci.com/pipelines/github/cucumber/cucumber/4639/workflows/e69feb45-ebed-4df0-adb4-5287f6d12f56/jobs/164798):

> Working copy is dirty. Please run 'source scripts/functions.sh && rsync_files' and commit modified files.

Cheers,
Aslak

**Comment by johnknoop** [comment]
Thanks for that @aslakhellesoy

I'm not sure I understand exactly how to run that script though. Is there some tooling I need to install first?

image

image

This is the first time I've cloned this repo, and I haven't done anything besides fixing the translation.

**Comment by mpkorstanje** [comment]
I don't think anybody in the core team uses wsl.

You may want to use the docker image to build Cucumber. I don't think anybody in the core team uses wsl. You can start it using `make docker-run` or copy/paste the commands from the Makefile.

**Comment by johnknoop** [comment]
Hi

I'm sorry, I can't seem to get that `docker run` command to execute successfully. I'm running git-bash on Windows. Here's the output:

image

I don't have a WSL distro installed unfortunately, so I can't run it on Linux.

What is `${HOME}/.m2/repository` referring to anyway? Something in my local user folder that I'm supposed to have?

**Comment by mpkorstanje** [comment]
Ah. I don't know git bash. 

The `.m2` directory would be your maven cache. But since you're not building maven you can omit the entire option. For `$(shell pwd)` you should replace that with your working directory.

**Comment by johnknoop** [comment]
Ah, now it ran successfully. But it doesn't seem to do anything to my working copy. After running the command, Docker attaches me to a terminal into the running container, but that seems to be all it's doing:

image

I have no changes to my local files. 🤔

**Comment by johnknoop** [comment]
@mpkorstanje Ah, got it. That seemed to propagate my change to a lot of other JSON files (see last commit).

I'm not 100% sure it ran correctly though, because the script output looked like this:

image

**Comment by mpkorstanje** [comment]
It's not ideal but to be expected. Because you're on windows you're mounting an NTFS file system in the container. NTFS does not support file attributes so they can't be set.

**Comment by johnknoop** [comment]
Well, please feel free to merge it anytime you like.

**Comment by aslakhellesoy** [comment]
Hi @johnknoop,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by mpkorstanje** [comment]
Not sure when I can roll out a release yet.

**Comment by johnknoop** [comment]
Hi @aslakhellesoy and thanks for that!

I probably won't be creating a lot of pull requests since I don't actually use Cucumber directly, but rather a bunch of derived tools like [jest-cucumber](https://github.com/bencompton/jest-cucumber), [SpecFlow](https://specflow.org/) and [cypress-cucumber-preprocessor](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor), and my hope is that this little translation I added will eventually trickle down to them.

But I might contribute anyway in some shape or form since the topic of specification by example is dear to me.

**Comment by mpkorstanje** [comment]
@aslakhellesoy I think this counts as a bug fix. WDYT?

**Pull request merged**
